Moved Feedback Submission to Server
kipr/Simulator pull request #310
Opened 2022-01-28 03:13 UTC by will-jac

Re-wrote the discord webhook submission to move it server-side, so that users can submit feedback even if discord is blocked, and without exposing the webhook URL to the public. Note that the final URL will need to be supplied as a server environmental variable, with the current URL functioning as a developer testing channel.

Other enhancements:

- Made the error text more helpful, allowing users to email kipr or open an issue if feedback submission fails (github link directs to the issues page because you are required to log in to github to open an issue, and this felt a little more natural"). Note that the email address may need to be changed or removed if that's not desired.
- Made the error text centered

Known bugs:

- Feedback form does not clear on submission. This was originally intentional, so that users could see what they said after the fact, but is definitely bad design. This is trivial to fix.
- The Modal dialog is not centered vertically on the screen

2022-01-28 10:37 UTC, bmcdorman requested changes
Thank you for the contribution! Let's switch to the discord.js API. It should clean up some of the request code.

2022-01-28 15:24 UTC, navzam commented
I'll add the env var and comment back here when it's ready. Let's hold off merging until then so we can test it in staging.

2022-01-31 05:12 UTC, will-jac commented
Changes should be resolved now!

2022-01-31 06:15 UTC, bmcdorman approved these changes

2022-01-31 06:24 UTC, merged