iRobotCreate
kipr/Simulator pull request #482
Opened 2023-12-08 21:29 UTC by chrismbirmingham

This pull request adds the iRobotCreate to the simulator. The create is defined using the same Robot interface as the demobot, but makes use of the create IO library for motor control and sensor reading. 

Additionally this pull request has moved files for better organization, documentation, and bug fixes.

2023-12-09 01:18 UTC, bmcdorman requested changes
There are a lot of style changes here that do not align with the rest of the codebase. I'd love to see these fixed.

2023-12-09 01:18 UTC, bmcdorman commented on dependencies/build.py
> +  # 'ammo': f'{ammo_build_dir}',
delete line rather than comment

2023-12-09 01:18 UTC, bmcdorman commented on express.js
> +              // console.log("Result successfully sent", data.toString());
nit: delete

2023-12-09 01:18 UTC, bmcdorman commented on src/BabylonBindings/RobotObjects/CreateBindings.ts
> +class CreateBinding {
Why is this file not named `CreateBinding`?

2023-12-09 01:18 UTC, bmcdorman commented on src/BabylonBindings/RobotObjects/MotorBindings.ts
> +import { Scene as babylScene, Quaternion, Vector3, Mesh,
This file should have a `camelCase` name if it is not a default class export

2023-12-09 01:18 UTC, bmcdorman commented on src/BabylonBindings/RobotObjects/MotorBindings.ts
> +export const createHinge_ = (id: string, hinge: Node.HingeJoint & { parentId: string }, bScene_: babylScene, bParent: Mesh, bChild: Mesh) => {
The `_` suffix is only for private class members

2023-12-09 01:18 UTC, bmcdorman commented on src/BabylonBindings/RobotObjects/RobotLink.ts
> +export const buildGeometry_ = async (name: string, geometry: Geometry, bScene_: babylScene): Promise<BuiltGeometry> => {
The `_` suffix is only for private class members.

2023-12-09 01:18 UTC, bmcdorman commented on src/BabylonBindings/RobotObjects/RobotLink.ts
> +export const createLink_ = async (id: string, link: Node.Link, bScene_: babylScene, robot_: Robot, colliders_: Set<Mesh>) => {
The `_` suffix is only for private class members.

2023-12-09 01:18 UTC, bmcdorman commented on src/BabylonBindings/RobotObjects/WeightBinding.ts
> +
File name should be `camelCase`

2023-12-09 01:18 UTC, bmcdorman commented on src/BabylonBindings/RobotObjects/WeightBinding.ts
> +export const createWeight_ = (id: string, weight: Node.Weight, bScene_: babylScene, robot_: Robot, links_: Dict<Mesh>) => {
The `_` suffix is only for private class members.

2023-12-09 01:18 UTC, bmcdorman commented on src/BabylonBindings/SceneObjects/CameraBinding.ts
> +export const createArcRotateCamera = (camera: Camera.ArcRotate, bScene_: babylScene): ArcRotateCamera => {
The `_` suffix is only for private class members.

2023-12-09 01:18 UTC, bmcdorman commented on src/BabylonBindings/SceneObjects/CameraBinding.ts
> +export const createNoneCamera = (camera: Camera.None, bScene_: babylScene): ArcRotateCamera => {
The `_` suffix is only for private class members.

2023-12-09 01:18 UTC, bmcdorman commented on src/BabylonBindings/SceneObjects/Lightbinding.ts
> +import { ShadowGenerator,  IShadowLight, PointLight, SpotLight, DirectionalLight,
This file name should be `camelCase`. Currently it obeys no naming scheme at all.

2023-12-09 01:18 UTC, bmcdorman commented on src/BabylonBindings/SceneObjects/Lightbinding.ts
> +export const createPointLight = (id: string, node: Node.PointLight, bScene_: babylScene, shadowGenerators_: Dict<ShadowGenerator>): PointLight => {
The `_` suffix is only for private class members.

2023-12-09 01:18 UTC, bmcdorman commented on src/BabylonBindings/SceneObjects/Lightbinding.ts
> +export const createDirectionalLight = (id: string, node: Node.DirectionalLight, bScene_: babylScene, shadowGenerators_: Dict<ShadowGenerator>): DirectionalLight => {
The `_` suffix is only for private class members.

2023-12-09 01:18 UTC, bmcdorman commented on src/BabylonBindings/SceneObjects/Lightbinding.ts
> +const createShadowGenerator_ = (light: IShadowLight) => {
The `_` suffix is only for private class members.

2023-12-09 01:18 UTC, bmcdorman commented on src/BabylonBindings/SceneObjects/MaterialBinding.ts
> +export const createMaterial = (id: string, material: Material, bScene_: babylScene) => {
The `_` suffix is only for private class members.

2023-12-09 01:18 UTC, bmcdorman commented on src/BabylonBindings/SceneObjects/MaterialBinding.ts
> +export const updateMaterialBasic = (bMaterial: StandardMaterial, material: Patch.InnerPatch<Material.Basic>, bScene_: babylScene) => {
The `_` suffix is only for private class members.

2023-12-09 01:18 UTC, bmcdorman commented on src/BabylonBindings/SceneObjects/MaterialBinding.ts
> +import { Texture, DynamicTexture, StandardMaterial, Color3, PBRMaterial,
File name should be `camelCase`.

2023-12-09 01:18 UTC, bmcdorman commented on src/BabylonBindings/SceneObjects/MaterialBinding.ts
> +export const updateMaterialPbr = (bMaterial: PBRMaterial, material: Patch.InnerPatch<Material.Pbr>, bScene_: babylScene) => {
The `_` suffix is only for private class members.

2023-12-09 01:18 UTC, bmcdorman commented on src/BabylonBindings/SceneObjects/ObjectBinding.ts
> +import { TransformNode, AbstractMesh, CreateBox, CreateSphere, CreateCylinder,
`camelCase`.

2023-12-09 01:18 UTC, bmcdorman commented on src/BabylonBindings/SceneObjects/ObjectBinding.ts
> +export const buildGeometry = async (name: string, geometry: Geometry, bScene_: babylScene, faceUvs?: RawVector2[]): Promise<FrameLike> => {
The `_` suffix is only for private class members.

2023-12-09 01:18 UTC, bmcdorman commented on src/BabylonBindings/SceneObjects/ObjectBinding.ts
> +export const createObject = async (node: Node.Obj, nextScene: Scene, parent: babylNode, bScene_: babylScene): Promise<babylNode> => {
The `_` suffix is only for private class members.

2023-12-09 01:18 UTC, bmcdorman commented on src/BabylonBindings/SceneObjects/ObjectBinding.ts
> +  }
The `_` suffix is only for private class members.

2023-12-09 01:18 UTC, bmcdorman commented on src/util/math/UnitMath.ts
>  // Contains math types that are tagged with units
make this file `camelCase` or retain current name.

2023-12-09 01:18 UTC, bmcdorman commented on src/util/math/UnitMath.ts
> +export interface Vector2wUnits {
What is a `2w`?

2023-12-09 01:18 UTC, bmcdorman commented on src/util/math/UnitMath.ts
> +  export interface EulerwUnits {
What is a `w`? Why doesn't it obey camel case?

2023-12-09 01:18 UTC, bmcdorman commented on src/util/math/UnitMath.ts
> +export interface ReferenceFramewUnits {
Again, this `w` makes no sense.

2023-12-09 01:18 UTC, bmcdorman commented on src/util/redux/deepNeq.ts
> +Type Comparison: Compares the types of value0 and value1. If they are of different
This comment is malformed. Every line should start with `*`

2023-12-09 01:18 UTC, bmcdorman commented on src/util/redux/deepNeq.ts
> +    Length Check: First, it checks if the arrays have different lengths. If so, it returns true.
Malformed

2023-12-09 01:18 UTC, bmcdorman commented on src/util/redux/deepNeq.ts
> +  Key Length Check: Compares the number of keys in each object. If they have
Malformed

2023-12-09 01:18 UTC, bmcdorman commented on src/state/reducer/robots.ts
> +import * as ROBOTS from '../../SimulatorDefinitions/robots';
why is the `PascalCase`? This pattern is not used anywhere in the code base.

2023-12-09 01:18 UTC, bmcdorman commented on src/state/reducer/documentation.ts
> +import { Size } from '../../components/Interface/Widget';
This shouldn't be `Interface`, it should be `interface`.

2023-12-09 01:18 UTC, bmcdorman commented on src/state/reducer/challengeCompletions.ts
> +import { ReferenceFramewUnits } from '../../util/math/UnitMath';
What is this `w`?

2023-12-09 01:18 UTC, bmcdorman commented on src/state/State/index.ts
> +import { Size } from '../../components/Interface/Widget';
Folder name shouldn't be `Interface`, it should be `interface`.

2023-12-09 01:18 UTC, bmcdorman commented on src/util/ParseMessages.ts
> +/**
Do not use `PascalCase`.

2023-12-09 01:20 UTC, bmcdorman commented on src/AbstractRobot/Motor.ts
> +  The Direction enumeration defines four possible directions for the motor: Idle, Forward, Backward, and Brake.
Comment needs `*`

2023-12-09 01:21 UTC, bmcdorman commented on src/App.tsx
> +import { DARK } from './components/Constants/theme';
Do not use `PascalCase` for things that aren't classes.

2024-01-05 22:09 UTC, tcorbly approved these changes

2024-01-18 07:43 UTC, tcorbly approved these changes

2024-01-18 07:46 UTC, merged